# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spot-mark-gene',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/spot-mark-gene',
                'lib_path': 'spot_mark_gene'},
  'syms': {'spot_mark_gene.core': {'spot_mark_gene.core.foo': ('core.html#foo', 'spot_mark_gene/core.py')}}}
