name: Deploy to GitHub Pages
on:  [workflow_dispatch, pull_request, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with:
          version: '3.10'